# Run Shiny Server as the 'shiny' user
run_as shiny;

server {
  listen 3838;

  # Serve your main app at the root URL
  location / {
    app_dir /srv/shiny-server/app;
  }

  # Optional logging
  log_dir /var/log/shiny-server;
}
